#pragma once

#include "Macro.h"
#include "Type.h"

#include "Buffer.h"
#include "DefaultAllocator.h"
#include "InPlace.h"
#include "Numeric.h"
#include "ParameterPackHelper.h"

#include "Template/AndOrNot.h"
#include "Template/BoolConstant.h"
#include "Template/Conditional.h"
#include "Template/EnableIf.h"
#include "Template/EnumUnderlyingType.h"
#include "Template/Forward.h"
#include "Template/Functional.h"
#include "Template/FunctionPointer.h"
#include "Template/IsArithmetic.h"
#include "Template/IsChar.h"
#include "Template/IsConstructible.h"
#include "Template/IsConvertible.h"
#include "Template/IsEnum.h"
#include "Template/IsEnumClass.h"
#include "Template/IsFloatPoint.h"
#include "Template/IsIntegral.h"
#include "Template/RemoveAllExtents.h"
#include "Template/RemoveAllPointers.h"
#include "Template/RemoveConst.h"
#include "Template/RemoveExtent.h"
#include "Template/RemovePointer.h"
#include "Template/RemoveReference.h"
#include "Template/SameAsAny.h"
#include "Template/SelectNthFromParameterPack.h"
#include "Template/TypesAreSame.h"