#pragma once

#include "Assert.h"
#include "Buffer.h"
#include "Build.h"
#include "ClassConstructorDestructor.h"
#include "CountArray.h"
#include "Enum.h"
#include "Forward.h"
#include "Function.h"
#include "InPlace.h"
#include "ParameterPack.h"
#include "PlacementNew.h"
#include "Span.h"
#include "Type.h"

#include "Allocator/DefaultAllocator.h"

#include "Mathematics/Numeric.h"

#include "Template/AndOrNot.h"
#include "Template/Conditional.h"
#include "Template/IsArithmetic.h"
#include "Template/IsChar.h"
#include "Template/IsConstructible.h"
#include "Template/IsConvertible.h"
#include "Template/IsFloatPoint.h"
#include "Template/IsIntegral.h"
#include "Template/RemoveAllExtents.h"
#include "Template/RemoveAllPointers.h"
#include "Template/RemoveAllQualifiers.h"
#include "Template/RemoveConst.h"
#include "Template/RemoveExtent.h"
#include "Template/RemovePointer.h"
#include "Template/RemoveReference.h"
#include "Template/SameAsAny.h"
#include "Template/TypesAreSame.h"